import { StyleSheet } from 'react-native';

// ─────────────────────────────────────────────
// SISTEMA DE TEMAS (claro / oscuro)
// ─────────────────────────────────────────────

export const THEMES = {
  light: {
    accent: '#2E9E65',
    accentDeep: '#1E6C38',
    accentSoft: '#E4F5E7',
    bg: '#EEF3F1',
    bgCard: '#FFFFFF',
    bgInput: '#F6FAF7',
    bgSwitch: '#E2EDE6',
    border: '#D6E4DB',
    borderCard: 'rgba(46,158,101,0.12)',
    text: '#1A2E23',
    textMuted: '#617180',
    textLabel: '#375246',
    textHelper: '#75847D',
    textSwitch: '#5A7A68',
    error: '#D9485F',
    errorBg: '#FFF0F2',
    noticeBg: '#EDFAF3',
    shadow: '#183247',
    logoGlow: 'rgba(46,158,101,0.22)',
    chipBg: 'rgba(46,158,101,0.1)',
    chipText: '#2E6B4A',
    footerText: '#A0B0A8',
  },
  dark: {
    accent: '#3DBF7A',
    accentDeep: '#2E9E65',
    accentSoft: '#1A3328',
    bg: '#0F1F18',
    bgCard: '#182820',
    bgInput: '#1E3228',
    bgSwitch: '#1A2E22',
    border: '#2A4035',
    borderCard: 'rgba(61,191,122,0.18)',
    text: '#E8F5EE',
    textMuted: '#7FAE94',
    textLabel: '#9ECFB3',
    textHelper: '#5D8472',
    textSwitch: '#6BA882',
    error: '#FF6B7A',
    errorBg: '#2A1820',
    noticeBg: '#142B20',
    shadow: '#000000',
    logoGlow: 'rgba(61,191,122,0.30)',
    chipBg: 'rgba(61,191,122,0.12)',
    chipText: '#5AD492',
    footerText: '#3A5C48',
  },
};

export function getTheme(isDark) {
  return isDark ? THEMES.dark : THEMES.light;
}

export function getAuthStyles(isDark) {
  const t = getTheme(isDark);

  return StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: t.bg,
    },
    content: {
      paddingHorizontal: 22,
      paddingTop: 20,
      paddingBottom: 40,
      flexGrow: 1,
      gap: 26,
    },

    // ── Hero ──
    hero: {
      alignItems: 'center',
      gap: 16,
      paddingTop: 10,
    },
    logoGlow: {
      width: 108,
      height: 108,
      borderRadius: 54,
      backgroundColor: t.logoGlow,
      alignItems: 'center',
      justifyContent: 'center',
    },
    logoBox: {
      width: 84,
      height: 84,
      borderRadius: 26,
      backgroundColor: t.accent,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: t.accentDeep,
      shadowOpacity: 0.4,
      shadowRadius: 20,
      shadowOffset: { width: 0, height: 10 },
      elevation: 8,
    },
    logo: {
      width: 54,
      height: 54,
    },
    heroText: {
      alignItems: 'center',
      gap: 8,
    },
    title: {
      color: t.text,
      fontSize: 36,
      fontWeight: '900',
      letterSpacing: -1,
      textAlign: 'center',
    },
    titleAccent: {
      color: t.accent,
    },
    subtitle: {
      color: t.textMuted,
      fontSize: 14,
      lineHeight: 21,
      textAlign: 'center',
      maxWidth: 300,
    },
    chipRow: {
      flexDirection: 'row',
      gap: 8,
      flexWrap: 'wrap',
      justifyContent: 'center',
    },
    chip: {
      backgroundColor: t.chipBg,
      borderRadius: 999,
      paddingHorizontal: 12,
      paddingVertical: 6,
    },
    chipText: {
      color: t.chipText,
      fontSize: 12,
      fontWeight: '700',
    },

    // ── Card ──
    card: {
      backgroundColor: t.bgCard,
      borderRadius: 32,
      padding: 22,
      gap: 20,
      borderWidth: 1.5,
      borderColor: t.borderCard,
      shadowColor: t.shadow,
      shadowOpacity: isDark ? 0.5 : 0.1,
      shadowRadius: 28,
      shadowOffset: { width: 0, height: 14 },
      elevation: 10,
    },

    // ── Switch ──
    switchTrack: {
      flexDirection: 'row',
      backgroundColor: t.bgSwitch,
      borderRadius: 20,
      padding: 4,
    },
    switchBtn: {
      flex: 1,
      borderRadius: 16,
      paddingVertical: 13,
      alignItems: 'center',
    },
    switchBtnActive: {
      backgroundColor: t.accent,
      shadowColor: t.accentDeep,
      shadowOpacity: 0.3,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 4 },
      elevation: 4,
    },
    switchText: {
      color: t.textSwitch,
      fontWeight: '700',
      fontSize: 14,
    },
    switchTextActive: {
      color: '#FFFFFF',
      letterSpacing: 0.2,
    },

    // ── Form ──
    form: {
      gap: 14,
    },
    inputGroup: {
      gap: 7,
    },
    inputLabel: {
      color: t.textLabel,
      fontSize: 13,
      fontWeight: '700',
      letterSpacing: 0.3,
      textTransform: 'uppercase',
    },
    inputWrapper: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: t.bgInput,
      borderWidth: 1.5,
      borderColor: t.border,
      borderRadius: 16,
      paddingHorizontal: 14,
      paddingVertical: 2,
      gap: 10,
    },
    inputWrapperError: {
      borderColor: t.error,
    },
    inputIcon: {
      fontSize: 16,
    },
    inputField: {
      flex: 1,
      paddingVertical: 13,
      color: t.text,
      fontSize: 15,
    },
    inputError: {
      color: t.error,
      fontSize: 12,
      fontWeight: '600',
    },

    // ── Submit ──
    submitBtn: {
      borderRadius: 18,
      marginTop: 4,
      overflow: 'hidden',
      backgroundColor: t.accent,
      shadowColor: t.accentDeep,
      shadowOpacity: 0.35,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 6 },
      elevation: 6,
    },
    submitBtnDisabled: {
      opacity: 0.55,
    },
    submitBtnPressed: {
      opacity: 0.85,
      transform: [{ scale: 0.98 }],
    },
    submitBtnInner: {
      paddingVertical: 16,
      alignItems: 'center',
    },
    submitBtnText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '800',
      letterSpacing: 0.5,
    },

    // ── Feedback ──
    alertBox: {
      backgroundColor: t.errorBg,
      borderRadius: 12,
      padding: 12,
      borderLeftWidth: 3,
      borderLeftColor: t.error,
    },
    alertText: {
      color: t.error,
      fontSize: 13,
      fontWeight: '600',
    },
    noticeBox: {
      backgroundColor: t.noticeBg,
      borderRadius: 12,
      padding: 12,
      borderLeftWidth: 3,
      borderLeftColor: t.accent,
    },
    noticeText: {
      color: t.accent,
      fontSize: 13,
      fontWeight: '600',
    },

    // ── Misc ──
    helper: {
      color: t.textHelper,
      fontSize: 13,
      lineHeight: 19,
      textAlign: 'center',
    },
    footer: {
      color: t.footerText,
      fontSize: 12,
      textAlign: 'center',
      letterSpacing: 0.5,
    },

    // Mantener compatibilidad con ProfileScreen que usa estos estilos
    inputDisabled: {
      backgroundColor: isDark ? '#1A2E22' : '#EEF3F1',
      borderWidth: 1,
      borderColor: t.border,
      borderRadius: 16,
      paddingHorizontal: 16,
      paddingVertical: 14,
      color: isDark ? '#4A6858' : '#65736B',
      fontSize: 15,
    },
  });
}

export const styles = StyleSheet.create({
  // Los estilos de auth legacy se mantienen por compatibilidad
  authScreen: {
    flex: 1,
    backgroundColor: '#EEF3F1',
  },
  authContent: {
    padding: 24,
    justifyContent: 'center',
    flexGrow: 1,
    gap: 24,
  },
  authHero: {
    alignItems: 'center',
    gap: 14,
  },
  authLogoBox: {
    width: 88,
    height: 88,
    borderRadius: 26,
    backgroundColor: '#44B96B',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#1E6C38',
    shadowOpacity: 0.24,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  authLogo: {
    width: 56,
    height: 56,
  },
  authTitle: {
    color: '#26465D',
    fontSize: 30,
    lineHeight: 36,
    fontWeight: '800',
    textAlign: 'center',
  },
  authSubtitle: {
    color: '#617180',
    fontSize: 15,
    lineHeight: 22,
    textAlign: 'center',
    maxWidth: 340,
  },
  authCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 28,
    padding: 20,
    gap: 18,
    shadowColor: '#183247',
    shadowOpacity: 0.1,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 12 },
    elevation: 6,
  },
  authSwitch: {
    flexDirection: 'row',
    backgroundColor: '#E8F0EB',
    borderRadius: 18,
    padding: 4,
  },
  authSwitchButton: {
    flex: 1,
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: 'center',
  },
  authSwitchButtonActive: {
    backgroundColor: '#2E9E65',
  },
  authSwitchText: {
    color: '#668171',
    fontWeight: '700',
  },
  authSwitchTextActive: {
    color: '#FFFFFF',
  },
  formBlock: {
    gap: 14,
  },
  inputGroup: {
    gap: 8,
  },
  inputLabel: {
    color: '#375246',
    fontSize: 14,
    fontWeight: '700',
  },
  input: {
    backgroundColor: '#F6FAF7',
    borderWidth: 1,
    borderColor: '#D6E4DB',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    color: '#1E2F26',
    fontSize: 15,
  },
  inputDisabled: {
    backgroundColor: '#EEF3F1',
    borderWidth: 1,
    borderColor: '#D6E4DB',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    color: '#65736B',
    fontSize: 15,
  },
  inputError: {
    borderColor: '#D9485F',
  },
  errorText: {
    color: '#D9485F',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 2,
  },
  submitButton: {
    backgroundColor: '#2E9E65',
    borderRadius: 18,
    paddingVertical: 15,
    alignItems: 'center',
    marginTop: 6,
  },
  submitButtonDisabled: {
    opacity: 0.65,
  },
  submitButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
  },
  formErrorText: {
    color: '#D9485F',
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
  },
  formNoticeText: {
    color: '#238B57',
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
  },
  helperText: {
    color: '#75847D',
    fontSize: 13,
    lineHeight: 19,
    textAlign: 'center',
  },
  appShell: {
    flex: 1,
    backgroundColor: '#E9EFED',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  phoneShell: {
    flex: 1,
    backgroundColor: '#FDFDFB',
    borderRadius: 30,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#D7E2DB',
  },
  screenContent: {
    padding: 18,
    paddingBottom: 96,
    gap: 16,
  },
  topHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  greeting: {
    color: '#334544',
    fontSize: 28,
    fontWeight: '800',
  },
  subGreeting: {
    color: '#7D8D85',
    fontSize: 13,
    marginTop: 4,
  },
  iconBadge: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: '#E2F4E8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconBadgeText: {
    color: '#2E9E65',
    fontSize: 20,
  },
  pointsHero: {
    backgroundColor: '#2EAF74',
    borderRadius: 22,
    padding: 18,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#2E9E65',
    shadowOpacity: 0.25,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  pointsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  locationDot: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#FFFFFF',
  },
  pointsValue: {
    color: '#FFFFFF',
    fontSize: 28,
    fontWeight: '800',
  },
  pointsCaption: {
    color: '#DDF4E8',
    fontSize: 13,
    marginTop: 4,
  },
  heroIcon: {
    width: 78,
    height: 78,
  },
  statRow: {
    flexDirection: 'row',
    gap: 10,
  },
  statMiniCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E3ECE6',
  },
  statMiniIcon: {
    fontSize: 16,
  },
  statMiniValue: {
    color: '#2D3D37',
    fontSize: 18,
    fontWeight: '800',
    marginTop: 8,
  },
  statMiniLabel: {
    color: '#7C8B83',
    fontSize: 12,
    marginTop: 3,
  },
  actionCard: {
    borderRadius: 22,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  actionCardGreen: {
    backgroundColor: '#E4F5E7',
  },
  actionCardGold: {
    backgroundColor: '#FFF2C8',
  },
  actionIconCircle: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionIconText: {
    fontSize: 21,
    color: '#2E9E65',
  },
  actionTextBlock: {
    flex: 1,
    gap: 5,
  },
  actionTitle: {
    color: '#2E3F35',
    fontSize: 24,
    fontWeight: '800',
  },
  actionSubtitle: {
    color: '#7A887F',
    fontSize: 13,
    lineHeight: 18,
  },
  plusPill: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#8BC34A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  plusPillText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '800',
  },
  materialRow: {
    flexDirection: 'row',
    gap: 10,
  },
  materialCard: {
    flex: 1,
    backgroundColor: '#F5F7F2',
    borderRadius: 18,
    padding: 14,
    alignItems: 'center',
  },
  materialValue: {
    color: '#48624F',
    fontSize: 20,
    fontWeight: '800',
  },
  materialLabel: {
    color: '#92A098',
    fontSize: 12,
    marginTop: 3,
  },
  searchCard: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 8,
    borderWidth: 1,
    borderColor: '#DDE7E0',
  },
  searchInput: {
    flex: 1,
    paddingHorizontal: 12,
    color: '#32453B',
  },
  searchButton: {
    width: 44,
    borderRadius: 14,
    backgroundColor: '#2E9E65',
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchButtonText: {
    color: '#FFFFFF',
    fontSize: 20,
  },
  filterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  filterPill: {
    backgroundColor: '#EAF4ED',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  filterPillText: {
    color: '#467458',
    fontSize: 12,
    fontWeight: '700',
  },
  mapMock: {
    height: 360,
    borderRadius: 28,
    backgroundColor: '#EEF1EA',
    overflow: 'hidden',
    position: 'relative',
  },
  mapStreetHorizontal: {
    position: 'absolute',
    top: '36%',
    left: -20,
    right: -20,
    height: 64,
    backgroundColor: '#FAFAF7',
    transform: [{ rotate: '-18deg' }],
    borderTopWidth: 2,
    borderBottomWidth: 2,
    borderColor: '#D9DED4',
  },
  mapStreetVertical: {
    position: 'absolute',
    top: '8%',
    bottom: '8%',
    left: '44%',
    width: 64,
    backgroundColor: '#FAFAF7',
    transform: [{ rotate: '12deg' }],
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderColor: '#D9DED4',
  },
  mapPark: {
    position: 'absolute',
    width: 118,
    height: 94,
    borderRadius: 26,
    backgroundColor: '#D6F0C8',
    top: '45%',
    left: '36%',
  },
  pin: {
    position: 'absolute',
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.16,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  pinText: {
    color: '#FFFFFF',
    fontSize: 18,
  },
  locationCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E2EAE3',
    marginTop: -70,
    marginHorizontal: 10,
    shadowColor: '#294335',
    shadowOpacity: 0.12,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  locationCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  locationTitle: {
    color: '#33453D',
    fontSize: 28,
    fontWeight: '800',
  },
  locationSubtitle: {
    color: '#7F8F87',
    fontSize: 14,
    marginTop: 4,
  },
  locationClose: {
    color: '#8C9791',
    fontSize: 26,
  },
  locationImage: {
    backgroundColor: '#D7EFD5',
    borderRadius: 18,
    height: 90,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
  },
  locationImageIcon: {
    width: 70,
    height: 70,
  },
  locationDescription: {
    color: '#6F8077',
    fontSize: 13,
    marginTop: 12,
    textAlign: 'center',
  },
  primaryCta: {
    backgroundColor: '#21A673',
    borderRadius: 18,
    alignItems: 'center',
    paddingVertical: 14,
    marginTop: 14,
  },
  primaryCtaText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
  },
  rewardsHero: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    padding: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    borderWidth: 1,
    borderColor: '#E1EBE3',
  },
  rewardsBadge: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: '#DDF2E4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  rewardsBadgeText: {
    color: '#2E9E65',
    fontSize: 28,
  },
  rewardsSummary: {
    flex: 1,
  },
  rewardsValue: {
    color: '#293D34',
    fontSize: 30,
    fontWeight: '800',
  },
  rewardsSmall: {
    color: '#809087',
    fontSize: 13,
    marginTop: 4,
  },
  panel: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    padding: 16,
    gap: 14,
    borderWidth: 1,
    borderColor: '#E1EBE3',
  },
  panelHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  panelTitle: {
    color: '#2E3E37',
    fontSize: 20,
    fontWeight: '800',
  },
  panelLink: {
    color: '#2E9E65',
    fontSize: 13,
    fontWeight: '700',
  },
  rewardItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  rewardIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: '#E5F3E8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  rewardIconText: {
    color: '#2E9E65',
    fontSize: 18,
  },
  rewardTextBlock: {
    flex: 1,
    gap: 6,
  },
  rewardTitle: {
    color: '#384841',
    fontSize: 15,
    fontWeight: '700',
  },
  rewardBarTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: '#EDF2ED',
    overflow: 'hidden',
  },
  rewardBarFill: {
    height: '100%',
    borderRadius: 999,
  },
  rewardPoints: {
    fontSize: 18,
    fontWeight: '800',
  },
  achievementRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  achievementIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: '#FFF5D7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  achievementIconText: {
    color: '#E3A300',
    fontSize: 18,
  },
  achievementTitle: {
    color: '#31433A',
    fontSize: 15,
    fontWeight: '700',
  },
  achievementLevel: {
    color: '#84938B',
    fontSize: 13,
    marginTop: 3,
  },
  profileHeader: {
    alignItems: 'center',
    gap: 8,
    paddingVertical: 14,
  },
  avatar: {
    width: 86,
    height: 86,
    borderRadius: 43,
    backgroundColor: '#DDF2E4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    color: '#2E9E65',
    fontSize: 34,
    fontWeight: '800',
  },
  profileName: {
    color: '#2D3F37',
    fontSize: 24,
    fontWeight: '800',
  },
  profileEmail: {
    color: '#819188',
    fontSize: 14,
  },
  profileScoreCard: {
    backgroundColor: '#E8F5EB',
    borderRadius: 22,
    padding: 18,
    gap: 6,
  },
  profileScoreTitle: {
    color: '#48705A',
    fontSize: 14,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  profileScoreValue: {
    color: '#294137',
    fontSize: 26,
    fontWeight: '800',
  },
  profileScoreHint: {
    color: '#6F8278',
    fontSize: 13,
    lineHeight: 18,
  },
  profileOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#EEF2EE',
  },
  profileOptionText: {
    color: '#34463E',
    fontSize: 15,
    fontWeight: '600',
  },
  profileOptionArrow: {
    color: '#98A49D',
    fontSize: 22,
  },
  historyItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  historyBadge: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: '#E4F5E7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  historyBadgeText: {
    color: '#2E9E65',
    fontSize: 14,
    fontWeight: '800',
  },
  historyTextBlock: {
    flex: 1,
    gap: 4,
  },
  historyTitle: {
    color: '#31433A',
    fontSize: 15,
    fontWeight: '700',
  },
  historySubtitle: {
    color: '#7A887F',
    fontSize: 12,
    lineHeight: 17,
  },
  historyDate: {
    color: '#94A098',
    fontSize: 12,
    fontWeight: '700',
  },
  notificationSettingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  notificationSettingText: {
    flex: 1,
    gap: 4,
  },
  notificationToggle: {
    minWidth: 58,
    borderRadius: 999,
    backgroundColor: '#DCE3DE',
    paddingHorizontal: 12,
    paddingVertical: 8,
    alignItems: 'center',
  },
  notificationToggleOn: {
    backgroundColor: '#2E9E65',
  },
  notificationToggleText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
  },
  tabBar: {
    position: 'absolute',
    left: 14,
    right: 14,
    bottom: 12,
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#DDE7E0',
    shadowColor: '#33493E',
    shadowOpacity: 0.1,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  tabItem: {
    flex: 1,
    alignItems: 'center',
    gap: 4,
  },
  tabIcon: {
    color: '#9AA49F',
    fontSize: 18,
  },
  tabIconActive: {
    color: '#2E9E65',
  },
  tabLabel: {
    color: '#97A39D',
    fontSize: 11,
    fontWeight: '700',
  },
  tabLabelActive: {
    color: '#2E9E65',
  },
});
